class htcondorce::config {

  file { 'ProbeConfig':
    ensure  => file,
    path    => '/etc/gratia/slurm/ProbeConfig',
    owner   => 'root',
    group   => 'root',
    mode    => '0644',
    content => template('htcondorce/ProbeConfig.erb'),
#    require => Package['gratia-probe-slurm'],
  }

  file { '01-squid.ini':
    ensure  => file,
    path    => '/etc/osg/config.d/01-squid.ini',
    owner   => 'root',
    group   => 'root',
    mode    => '0644',
    content => template('htcondorce/osg/config.d/01-squid.ini.erb'),
    notify  => Exec['osg-configure'],
  }

  file { '10-gateway.ini':
    ensure  => file,
    path    => '/etc/osg/config.d/10-gateway.ini',
    owner   => 'root',
    group   => 'root',
    mode    => '0644',
    source  => 'puppet:///modules/htcondorce/osg/config.d/10-gateway.ini',
    notify  => Exec['osg-configure'],
  }

  file { '10-misc.ini':
    ensure  => file,
    path    => '/etc/osg/config.d/10-misc.ini',
    owner   => 'root',
    group   => 'root',
    mode    => '0644',
    content => template('htcondorce/osg/config.d/10-misc.ini.erb'),
    notify  => Exec['osg-configure'],
  }

  file { '10-storage.ini':
    ensure  => file,
    path    => '/etc/osg/config.d/10-storage.ini',
    owner   => 'root',
    group   => 'root',
    mode    => '0644',
    content  => template('htcondorce/osg/config.d/10-storage.ini.erb'),
    notify  => Exec['osg-configure'],
  }

  file { '20-pbs.ini':
    ensure  => file,
    path    => '/etc/osg/config.d/20-pbs.ini',
    owner   => 'root',
    group   => 'root',
    mode    => '0644',
    content => template('htcondorce/osg/config.d/20-pbs.ini.erb'),
    notify  => Exec['osg-configure'],
  }

  file { '30-gip.ini':
    ensure  => file,
    path    => '/etc/osg/config.d/30-gip.ini',
    owner   => 'root',
    group   => 'root',
    mode    => '0644',
    source  => 'puppet:///modules/htcondorce/osg/config.d/30-gip.ini',
    notify  => Exec['osg-configure'],
  }

  file { '30-infoservices.ini':
    ensure  => file,
    path    => '/etc/osg/config.d/30-infoservices.ini',
    owner   => 'root',
    group   => 'root',
    mode    => '0644',
    source  => 'puppet:///modules/htcondorce/osg/config.d/30-infoservices.ini',
    notify  => Exec['osg-configure'],
  }

  file { '40-siteinfo.ini':
    ensure  => file,
    path    => '/etc/osg/config.d/40-siteinfo.ini',
    owner   => 'root',
    group   => 'root',
    mode    => '0644',
    content => template('htcondorce/osg/config.d/40-siteinfo.ini.erb'),
    notify  => Exec['osg-configure'],
  }

  exec {"gums-host-cron":
      path        => "/bin:/usr/bin:/sbin:/usr/sbin",
      command     => "gums-host-cron",
      logoutput   => "on_failure",
  }

  exec {"osg-configure":
      path        => "/bin:/usr/bin:/sbin:/usr/sbin",
      command     => "osg-configure -c",
      logoutput   => "on_failure",
  }

  #generated by command "osg-configure -c"
  #file { 'osg-job-environment.conf':
  #  ensure  => file,
  #  path    => '/var/lib/osg/osg-job-environment.conf',
  #  owner   => 'root',
  #  group   => 'root',
  #  mode    => '0644',
  #  source  => 'puppet:///modules/htcondorce/var/lib/osg/osg-job-environment.conf',
  #}

  #generated by command "osg-configure -c"
  #file { 'osg-local-job-environment.conf':
  #  ensure  => file,
  #  path    => '/var/lib/osg/osg-local-job-environment.conf',
  #  owner   => 'root',
  #  group   => 'root',
  #  mode    => '0644',
  #  source  => 'puppet:///modules/htcondorce/var/lib/osg/osg-local-job-environment.conf',
  #}

  file { 'blah.config':
    path    => '/etc/blah.config',
    ensure  => file,
    owner   => 'root',
    group   => 'root',
    mode    => '0644',
    source  => 'puppet:///modules/htcondorce/blah.config',
  }

  file { 'condor-ce-01-ce-auth':
    ensure  => present,
    path    => '/etc/condor-ce/config.d/01-ce-auth.conf',
    owner   => 'root',
    group   => 'root',
    mode    => '0644',
    source  => 'puppet:///modules/htcondorce/condor-ce/config.d/01-ce-auth.conf',
    notify  => Service['condor-ce'],
  }

  file { 'condor-ce-hcc-config':
    ensure  => present,
    path    => '/etc/condor-ce/config.d/09-hcc-tuning.conf',
    owner   => 'root',
    group   => 'root',
    mode    => '0644',
    source  => 'puppet:///modules/htcondorce/condor-ce/config.d/09-hcc-tuning.conf',
    notify  => Service['condor-ce'],
  }

}
